# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20170622_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='member/'),
        ),
    ]
