# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 05:23
from __future__ import unicode_literals

from django.db import migrations
import utils.fields.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_user_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=utils.fields.custom_imagefield.CustomImageField(blank=True, null=True, upload_to='member/'),
        ),
    ]
