# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import utils.fields.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20170626_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=utils.fields.custom_imagefield.CustomImageField(blank=True, default='', upload_to='member/'),
            preserve_default=False,
        ),
    ]
