# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postlike_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='created_date',
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='post_post_like_users',
        ),
    ]
