# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_thumbnail_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
