# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20170714_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
