# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_like_count',
        ),
    ]
