# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_post_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
